language: csharp
solution: GameFrameTests.sln

install:
  - sudo apt-get install nunit-console
  
before_script:
  - nuget restore GameFrameTests.sln
script:
  - xbuild GameFrameTests.sln
  - cd GameFrame.Tests
  - ls
  - cd bin
  - ls
  - cd Debug
  - nunit-console GameFrame.Tests.dll